services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: node:22.14
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
  
volumes:
  postgres-data: